name: Deploy to Firebase Hosting on merge

'on':
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      
      - name: Flutter Pub Get
        run: flutter pub get
      
      # Modified build command with additional flags
      - name: Build Flutter Web App
        env:
          GOOGLE_AI_API_KEY: ${{ secrets.GOOGLE_AI_API_KEY }}
          DEEPGRAM_API_KEY: ${{ secrets.DEEPGRAM_API_KEY }}
        run: |
          flutter clean
          flutter build web --release \
            --web-renderer html \
            --dart-define=GOOGLE_AI_API_KEY="$GOOGLE_AI_API_KEY" \
            --dart-define=DEEPGRAM_API_KEY="$DEEPGRAM_API_KEY" \
            --no-tree-shake-icons

      # Add step to modify index.html
      - name: Modify index.html for dart-define
        run: |
          sed -i 's/<script src="main.dart.js"/<script src="main.dart.js?version='$(date +%s)'"/' build/web/index.html
      
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_FLUENCY_PRACTICE }}'
          channelId: live
          projectId: fluency-practice
        env:
          FIREBASE_CLI_EXPERIMENTS: webframeworks